{
 "title": "Lecture GraalVM",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1s, 2s, 5s, 10s, 15s, 30s, 1m" },
   { "name": "step", "label": "step", "query": "1s, 2s, 5s, 10s, 15s, 30s, 1m" },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{name=~\"graalvm-demo-book.*\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(topk(1, time() - container_start_time_seconds{name=~\"graalvm-demo-book-.*\"}) by (name), \"name\", \"$1\", \"name\", \"graalvm-demo-book-(.*)\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resource Usage (graalvm-demo-book)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "CPU Time Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by (name) (container_cpu_usage_seconds_total{name=~\"$container\", name!=\"graalvm-demo-book-utilizer\"}), \"name\", \"$1\", \"name\", \"graalvm-demo-book-(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by (name) (container_cpu_usage_seconds_total{name=~\"$container\", name!=\"graalvm-demo-book-utilizer\"}), \"name\", \"$1\", \"name\", \"graalvm-demo-book-(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "100% means utilization of 1 core",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{name=~\"$container\", name!=\"graalvm-demo-book-utilizer\"}[$interval])) by (name), \"name\", \"$1\", \"name\", \"graalvm-demo-book-(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Max)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by (name) (container_memory_rss{name=~\"$container\", name!=\"graalvm-demo-book-utilizer\"}), \"name\", \"$1\", \"name\", \"graalvm-demo-book-(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Max)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by (name) (container_memory_rss{name=~\"$container\", name!=\"graalvm-demo-book-utilizer\"}), \"name\", \"$1\", \"name\", \"graalvm-demo-book-(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_rss{name=~\"$container\", name!=\"graalvm-demo-book-utilizer\"}) by (name), \"name\", \"$1\", \"name\", \"graalvm-demo-book-(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by (name) (container_fs_usage_bytes{name=~\"$container\", name!=\"graalvm-demo-book-utilizer\"}), \"name\", \"$1\", \"name\", \"graalvm-demo-book-(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by (name) (container_fs_usage_bytes{name=~\"$container\", name!=\"graalvm-demo-book-utilizer\"}), \"name\", \"$1\", \"name\", \"graalvm-demo-book-(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(sum by (name) (container_fs_usage_bytes{name=~\"$container\", name!=\"graalvm-demo-book-utilizer\"}), \"name\", \"$1\", \"name\", \"graalvm-demo-book-(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Usage (others)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage Mongo",
     "type": "timeseries",
     "description": "100% means utilization of 1 core",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"mongo\"}[$interval])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage Mongo",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{name=\"mongo\"}) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage Utilizer",
     "type": "timeseries",
     "description": "100% means utilization of 1 core",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{name=\"graalvm-demo-book-utilizer\"}[$interval])) by (name), \"name\", \"$1\", \"name\", \"graalvm-demo-book-(.*)\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage Utilizer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(sum(container_memory_rss{name=\"graalvm-demo-book-utilizer\"}) by (name), \"name\", \"$1\", \"name\", \"graalvm-demo-book-(.*)\")",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Requests (graalvm-demo-book)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Connections: Open",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tomcat_connections_current_connections{service=~\"$container\"}",
       "legendFormat": "{{variant}}"
      }
     ]
    },
    {
     "title": "Server Connections: Completed Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{service=~\"$container\", uri=\"/books/bulk\"}[$interval])",
       "legendFormat": "{{variant}}"
      }
     ]
    },
    {
     "title": "Server Request Latency",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_bucket{service=~\"$container\",uri=\"/books/bulk\",outcome=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Server Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{service=~\"$container\",uri=\"/books/bulk\",outcome=\"SUCCESS\"}[$interval])) by (le,variant))",
       "legendFormat": "{{variant}} (p95)"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{service=~\"$container\",uri=\"/books/bulk\",outcome=\"SUCCESS\"}[$interval])) by (le,variant))",
       "legendFormat": "{{variant}} (p75)"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{service=~\"$container\",uri=\"/books/bulk\",outcome=\"SUCCESS\"}[$interval])) by (le,variant))",
       "legendFormat": "{{variant}} (p50)"
      },
      {
       "expr": "rate(http_server_requests_seconds_sum{service=~\"$container\", uri=\"/books/bulk\"}[$interval]) / rate(http_server_requests_seconds_count{service=~\"$container\", uri=\"/books/bulk\"}[5s])",
       "legendFormat": "{{variant}} (avg)"
      }
     ]
    },
    {
     "title": "Server Request Latency (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{service=~\"$container\", uri=\"/books/bulk\"}[5s]) / rate(http_server_requests_seconds_count{service=~\"$container\", uri=\"/books/bulk\"}[$interval])",
       "legendFormat": "{{variant}}"
      }
     ]
    },
    {
     "title": "Server Request Latency (25p)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.25, sum(rate(http_server_requests_seconds_bucket{service=~\"$container\",uri=\"/books/bulk\",outcome=\"SUCCESS\"}[$interval])) by (le,variant))",
       "legendFormat": "{{variant}} (p50)"
      }
     ]
    },
    {
     "title": "Server Request Latency (50p)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{service=~\"$container\",uri=\"/books/bulk\",outcome=\"SUCCESS\"}[$interval])) by (le,variant))",
       "legendFormat": "{{variant}} (p50)"
      }
     ]
    },
    {
     "title": "Server Request Latency (75p)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{service=~\"$container\",uri=\"/books/bulk\",outcome=\"SUCCESS\"}[$interval])) by (le,variant))",
       "legendFormat": "{{variant}} (p50)"
      }
     ]
    },
    {
     "title": "Server Request Latency (95p)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{service=~\"$container\",uri=\"/books/bulk\",outcome=\"SUCCESS\"}[$interval])) by (le,variant))",
       "legendFormat": "{{variant}} (p50)"
      }
     ]
    }
   ]
  }
 ]
}