services:
  graalvm-demo-book-jvm:
    container_name: graalvm-demo-book-jvm
    image: graalvm-demo-book-jvm-jlink-cds-aot:0.1.0
    build:
      context: .
      dockerfile: Dockerfile.jvm-jlink-cds-aot
    restart: always
    depends_on:
      - mongo
    environment:
      - SERVER_PORT=8080
      - SPRING_DATA_MONGODB_URI=mongodb://demo:graalvm@mongo:27017/demo?authSource=admin
      #- -Xlog:class+load:file=/tmp/cds.log
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '0.5'
        reservations:
          memory: '512M'
          cpus: '0.5'
    ports:
      - "8080:8080"

  graalvm-demo-book-native:
    container_name: graalvm-demo-book-native
    image: graalvm-demo-book-native:0.1.0
    build:
      context: .
      dockerfile: Dockerfile.native
    restart: always
    depends_on:
      - mongo
    environment:
      - SERVER_PORT=8080
      - SPRING_DATA_MONGODB_URI=mongodb://demo:graalvm@mongo:27017/demo?authSource=admin
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '0.5'
        reservations:
          memory: '512M'
          cpus: '0.5'
    ports:
      - "8081:8080"

  mongo:
    container_name: mongo
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: demo
      MONGO_INITDB_ROOT_PASSWORD: graalvm
    ports:
      - "27017:27017"
  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: demo
      ME_CONFIG_MONGODB_ADMINPASSWORD: graalvm
      ME_CONFIG_MONGODB_URL: mongodb://demo:graalvm@mongo:27017/
      ME_CONFIG_BASICAUTH: false
