server:
  tomcat:
    mbeanregistry:
      # Should be enabled for additional detailed Tomcat metrics
      enabled: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include : "*"

  prometheus:
    metrics:
      export:
        enabled: true
        step: 1s

  metrics:
    distribution:
      slo:
        http.server.requests: 500us,1ms,2ms,3ms,4ms,5ms,10ms,20ms,30ms,40ms,50ms,60ms,70ms,80ms,90ms,100ms,200ms,300ms,400ms,500ms,750ms,1s,5s

logging:
  level:
    root: INFO