global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'graalvm-demo-book-jvm'
    static_configs:
      - targets: ['graalvm-demo-book-jvm:8080']
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [job]
        action: replace
        target_label: service
      - target_label: variant
        replacement: jvm

  - job_name: 'graalvm-demo-book-native'
    static_configs:
      - targets: ['graalvm-demo-book-native:8080']
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [job]
        action: replace
        target_label: service
      - target_label: variant
        replacement: native